/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthShopifyRouteImport } from './routes/auth/shopify'
import { Route as ApiPublicShopifyRemindersRouteImport } from './routes/api/public/shopify/reminders'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthShopifyRoute = AuthShopifyRouteImport.update({
  id: '/auth/shopify',
  path: '/auth/shopify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicShopifyRemindersRoute =
  ApiPublicShopifyRemindersRouteImport.update({
    id: '/api/public/shopify/reminders',
    path: '/api/public/shopify/reminders',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/shopify': typeof AuthShopifyRoute
  '/api/public/shopify/reminders': typeof ApiPublicShopifyRemindersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/shopify': typeof AuthShopifyRoute
  '/api/public/shopify/reminders': typeof ApiPublicShopifyRemindersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/shopify': typeof AuthShopifyRoute
  '/api/public/shopify/reminders': typeof ApiPublicShopifyRemindersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth/shopify' | '/api/public/shopify/reminders'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth/shopify' | '/api/public/shopify/reminders'
  id: '__root__' | '/' | '/auth/shopify' | '/api/public/shopify/reminders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthShopifyRoute: typeof AuthShopifyRoute
  ApiPublicShopifyRemindersRoute: typeof ApiPublicShopifyRemindersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/shopify': {
      id: '/auth/shopify'
      path: '/auth/shopify'
      fullPath: '/auth/shopify'
      preLoaderRoute: typeof AuthShopifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/shopify/reminders': {
      id: '/api/public/shopify/reminders'
      path: '/api/public/shopify/reminders'
      fullPath: '/api/public/shopify/reminders'
      preLoaderRoute: typeof ApiPublicShopifyRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthShopifyRoute: AuthShopifyRoute,
  ApiPublicShopifyRemindersRoute: ApiPublicShopifyRemindersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
