/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRemindersRouteImport } from './routes/verify-reminders'
import { Route as RemindersRouteImport } from './routes/reminders'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthShopifyRouteImport } from './routes/auth/shopify'
import { Route as AuthShopifyCallbackRouteImport } from './routes/auth/shopify/callback'
import { Route as ApiPublicShopifyRemindersRouteImport } from './routes/api/public/shopify/reminders'
import { Route as ApiPublicHooksYearlyReemitRouteImport } from './routes/api/public/hooks/yearly-reemit'
import { Route as ApiPublicHooksSyncKlaviyoRouteImport } from './routes/api/public/hooks/sync-klaviyo'
import { Route as ApiPublicHooksSaveRemindersRouteImport } from './routes/api/public/hooks/save-reminders'

const VerifyRemindersRoute = VerifyRemindersRouteImport.update({
  id: '/verify-reminders',
  path: '/verify-reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const RemindersRoute = RemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthShopifyRoute = AuthShopifyRouteImport.update({
  id: '/auth/shopify',
  path: '/auth/shopify',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthShopifyCallbackRoute = AuthShopifyCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthShopifyRoute,
} as any)
const ApiPublicShopifyRemindersRoute =
  ApiPublicShopifyRemindersRouteImport.update({
    id: '/api/public/shopify/reminders',
    path: '/api/public/shopify/reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksYearlyReemitRoute =
  ApiPublicHooksYearlyReemitRouteImport.update({
    id: '/api/public/hooks/yearly-reemit',
    path: '/api/public/hooks/yearly-reemit',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSyncKlaviyoRoute =
  ApiPublicHooksSyncKlaviyoRouteImport.update({
    id: '/api/public/hooks/sync-klaviyo',
    path: '/api/public/hooks/sync-klaviyo',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSaveRemindersRoute =
  ApiPublicHooksSaveRemindersRouteImport.update({
    id: '/api/public/hooks/save-reminders',
    path: '/api/public/hooks/save-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/reminders': typeof RemindersRoute
  '/verify-reminders': typeof VerifyRemindersRoute
  '/auth/shopify': typeof AuthShopifyRouteWithChildren
  '/auth/shopify/callback': typeof AuthShopifyCallbackRoute
  '/api/public/hooks/save-reminders': typeof ApiPublicHooksSaveRemindersRoute
  '/api/public/hooks/sync-klaviyo': typeof ApiPublicHooksSyncKlaviyoRoute
  '/api/public/hooks/yearly-reemit': typeof ApiPublicHooksYearlyReemitRoute
  '/api/public/shopify/reminders': typeof ApiPublicShopifyRemindersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/reminders': typeof RemindersRoute
  '/verify-reminders': typeof VerifyRemindersRoute
  '/auth/shopify': typeof AuthShopifyRouteWithChildren
  '/auth/shopify/callback': typeof AuthShopifyCallbackRoute
  '/api/public/hooks/save-reminders': typeof ApiPublicHooksSaveRemindersRoute
  '/api/public/hooks/sync-klaviyo': typeof ApiPublicHooksSyncKlaviyoRoute
  '/api/public/hooks/yearly-reemit': typeof ApiPublicHooksYearlyReemitRoute
  '/api/public/shopify/reminders': typeof ApiPublicShopifyRemindersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/reminders': typeof RemindersRoute
  '/verify-reminders': typeof VerifyRemindersRoute
  '/auth/shopify': typeof AuthShopifyRouteWithChildren
  '/auth/shopify/callback': typeof AuthShopifyCallbackRoute
  '/api/public/hooks/save-reminders': typeof ApiPublicHooksSaveRemindersRoute
  '/api/public/hooks/sync-klaviyo': typeof ApiPublicHooksSyncKlaviyoRoute
  '/api/public/hooks/yearly-reemit': typeof ApiPublicHooksYearlyReemitRoute
  '/api/public/shopify/reminders': typeof ApiPublicShopifyRemindersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/reminders'
    | '/verify-reminders'
    | '/auth/shopify'
    | '/auth/shopify/callback'
    | '/api/public/hooks/save-reminders'
    | '/api/public/hooks/sync-klaviyo'
    | '/api/public/hooks/yearly-reemit'
    | '/api/public/shopify/reminders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/reminders'
    | '/verify-reminders'
    | '/auth/shopify'
    | '/auth/shopify/callback'
    | '/api/public/hooks/save-reminders'
    | '/api/public/hooks/sync-klaviyo'
    | '/api/public/hooks/yearly-reemit'
    | '/api/public/shopify/reminders'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/reminders'
    | '/verify-reminders'
    | '/auth/shopify'
    | '/auth/shopify/callback'
    | '/api/public/hooks/save-reminders'
    | '/api/public/hooks/sync-klaviyo'
    | '/api/public/hooks/yearly-reemit'
    | '/api/public/shopify/reminders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  RemindersRoute: typeof RemindersRoute
  VerifyRemindersRoute: typeof VerifyRemindersRoute
  AuthShopifyRoute: typeof AuthShopifyRouteWithChildren
  ApiPublicHooksSaveRemindersRoute: typeof ApiPublicHooksSaveRemindersRoute
  ApiPublicHooksSyncKlaviyoRoute: typeof ApiPublicHooksSyncKlaviyoRoute
  ApiPublicHooksYearlyReemitRoute: typeof ApiPublicHooksYearlyReemitRoute
  ApiPublicShopifyRemindersRoute: typeof ApiPublicShopifyRemindersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-reminders': {
      id: '/verify-reminders'
      path: '/verify-reminders'
      fullPath: '/verify-reminders'
      preLoaderRoute: typeof VerifyRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reminders': {
      id: '/reminders'
      path: '/reminders'
      fullPath: '/reminders'
      preLoaderRoute: typeof RemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/shopify': {
      id: '/auth/shopify'
      path: '/auth/shopify'
      fullPath: '/auth/shopify'
      preLoaderRoute: typeof AuthShopifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/shopify/callback': {
      id: '/auth/shopify/callback'
      path: '/callback'
      fullPath: '/auth/shopify/callback'
      preLoaderRoute: typeof AuthShopifyCallbackRouteImport
      parentRoute: typeof AuthShopifyRoute
    }
    '/api/public/shopify/reminders': {
      id: '/api/public/shopify/reminders'
      path: '/api/public/shopify/reminders'
      fullPath: '/api/public/shopify/reminders'
      preLoaderRoute: typeof ApiPublicShopifyRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/yearly-reemit': {
      id: '/api/public/hooks/yearly-reemit'
      path: '/api/public/hooks/yearly-reemit'
      fullPath: '/api/public/hooks/yearly-reemit'
      preLoaderRoute: typeof ApiPublicHooksYearlyReemitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-klaviyo': {
      id: '/api/public/hooks/sync-klaviyo'
      path: '/api/public/hooks/sync-klaviyo'
      fullPath: '/api/public/hooks/sync-klaviyo'
      preLoaderRoute: typeof ApiPublicHooksSyncKlaviyoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/save-reminders': {
      id: '/api/public/hooks/save-reminders'
      path: '/api/public/hooks/save-reminders'
      fullPath: '/api/public/hooks/save-reminders'
      preLoaderRoute: typeof ApiPublicHooksSaveRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthShopifyRouteChildren {
  AuthShopifyCallbackRoute: typeof AuthShopifyCallbackRoute
}

const AuthShopifyRouteChildren: AuthShopifyRouteChildren = {
  AuthShopifyCallbackRoute: AuthShopifyCallbackRoute,
}

const AuthShopifyRouteWithChildren = AuthShopifyRoute._addFileChildren(
  AuthShopifyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  RemindersRoute: RemindersRoute,
  VerifyRemindersRoute: VerifyRemindersRoute,
  AuthShopifyRoute: AuthShopifyRouteWithChildren,
  ApiPublicHooksSaveRemindersRoute: ApiPublicHooksSaveRemindersRoute,
  ApiPublicHooksSyncKlaviyoRoute: ApiPublicHooksSyncKlaviyoRoute,
  ApiPublicHooksYearlyReemitRoute: ApiPublicHooksYearlyReemitRoute,
  ApiPublicShopifyRemindersRoute: ApiPublicShopifyRemindersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
